/*
 * generated by Xtext 2.12.0
 */
package de.cooperateproject.modeling.textual.component.ide.contentassist.antlr;

import com.google.inject.Inject;
import de.cooperateproject.modeling.textual.component.ide.contentassist.antlr.internal.InternalComponentParser;
import de.cooperateproject.modeling.textual.component.services.ComponentGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ComponentParser extends AbstractContentAssistParser {

	@Inject
	private ComponentGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalComponentParser createParser() {
		InternalComponentParser result = new InternalComponentParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getClassifierRelationAccess().getAlternatives(), "rule__ClassifierRelation__Alternatives");
					put(grammarAccess.getClassifierAccess().getAlternatives(), "rule__Classifier__Alternatives");
					put(grammarAccess.getInterfaceRelationAccess().getAlternatives(), "rule__InterfaceRelation__Alternatives");
					put(grammarAccess.getMemberAccess().getAlternatives(), "rule__Member__Alternatives");
					put(grammarAccess.getComponentAccess().getAlternatives_2(), "rule__Component__Alternatives_2");
					put(grammarAccess.getComponentAccess().getAlternatives_3(), "rule__Component__Alternatives_3");
					put(grammarAccess.getInterfaceAccess().getAlternatives_2(), "rule__Interface__Alternatives_2");
					put(grammarAccess.getInterfaceAccess().getAlternatives_3(), "rule__Interface__Alternatives_3");
					put(grammarAccess.getConnectorAccess().getAlternatives_1(), "rule__Connector__Alternatives_1");
					put(grammarAccess.getProvideAccess().getAlternatives_2(), "rule__Provide__Alternatives_2");
					put(grammarAccess.getRequireAccess().getAlternatives_2(), "rule__Require__Alternatives_2");
					put(grammarAccess.getVisibilityAccess().getAlternatives(), "rule__Visibility__Alternatives");
					put(grammarAccess.getComponentDiagramAccess().getGroup(), "rule__ComponentDiagram__Group__0");
					put(grammarAccess.getRootPackageAccess().getGroup(), "rule__RootPackage__Group__0");
					put(grammarAccess.getComponentAccess().getGroup(), "rule__Component__Group__0");
					put(grammarAccess.getComponentAccess().getGroup_2_0(), "rule__Component__Group_2_0__0");
					put(grammarAccess.getComponentAccess().getGroup_3_1(), "rule__Component__Group_3_1__0");
					put(grammarAccess.getComponentAccess().getGroup_3_1_1(), "rule__Component__Group_3_1_1__0");
					put(grammarAccess.getGeneralizationAccess().getGroup(), "rule__Generalization__Group__0");
					put(grammarAccess.getAbstractionAccess().getGroup(), "rule__Abstraction__Group__0");
					put(grammarAccess.getManifestationAccess().getGroup(), "rule__Manifestation__Group__0");
					put(grammarAccess.getSubstitutionAccess().getGroup(), "rule__Substitution__Group__0");
					put(grammarAccess.getDependencyAccess().getGroup(), "rule__Dependency__Group__0");
					put(grammarAccess.getCommentAccess().getGroup(), "rule__Comment__Group__0");
					put(grammarAccess.getPortAccess().getGroup(), "rule__Port__Group__0");
					put(grammarAccess.getInterfaceAccess().getGroup(), "rule__Interface__Group__0");
					put(grammarAccess.getInterfaceAccess().getGroup_2_0(), "rule__Interface__Group_2_0__0");
					put(grammarAccess.getInterfaceAccess().getGroup_3_1(), "rule__Interface__Group_3_1__0");
					put(grammarAccess.getConnectorAccess().getGroup(), "rule__Connector__Group__0");
					put(grammarAccess.getConnectorAccess().getGroup_1_0(), "rule__Connector__Group_1_0__0");
					put(grammarAccess.getProvideAccess().getGroup(), "rule__Provide__Group__0");
					put(grammarAccess.getProvideAccess().getGroup_2_0(), "rule__Provide__Group_2_0__0");
					put(grammarAccess.getRequireAccess().getGroup(), "rule__Require__Group__0");
					put(grammarAccess.getRequireAccess().getGroup_2_0(), "rule__Require__Group_2_0__0");
					put(grammarAccess.getMethodAccess().getGroup(), "rule__Method__Group__0");
					put(grammarAccess.getMethodAccess().getGroup_6(), "rule__Method__Group_6__0");
					put(grammarAccess.getMethodAccess().getGroup_6_1(), "rule__Method__Group_6_1__0");
					put(grammarAccess.getMethodAccess().getGroup_8(), "rule__Method__Group_8__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
					put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
					put(grammarAccess.getComponentDiagramAccess().getTitleAssignment_2(), "rule__ComponentDiagram__TitleAssignment_2");
					put(grammarAccess.getComponentDiagramAccess().getRootpackageAssignment_3(), "rule__ComponentDiagram__RootpackageAssignment_3");
					put(grammarAccess.getRootPackageAccess().getNameAssignment_2(), "rule__RootPackage__NameAssignment_2");
					put(grammarAccess.getRootPackageAccess().getClassifiersAssignment_3(), "rule__RootPackage__ClassifiersAssignment_3");
					put(grammarAccess.getRootPackageAccess().getRelationsAssignment_4(), "rule__RootPackage__RelationsAssignment_4");
					put(grammarAccess.getComponentAccess().getNameAssignment_2_0_0(), "rule__Component__NameAssignment_2_0_0");
					put(grammarAccess.getComponentAccess().getAliasAssignment_2_0_2(), "rule__Component__AliasAssignment_2_0_2");
					put(grammarAccess.getComponentAccess().getNameAssignment_2_1(), "rule__Component__NameAssignment_2_1");
					put(grammarAccess.getComponentAccess().getCommentsAssignment_3_0(), "rule__Component__CommentsAssignment_3_0");
					put(grammarAccess.getComponentAccess().getCommentsAssignment_3_1_1_0(), "rule__Component__CommentsAssignment_3_1_1_0");
					put(grammarAccess.getComponentAccess().getComponentAssignment_3_1_1_1(), "rule__Component__ComponentAssignment_3_1_1_1");
					put(grammarAccess.getComponentAccess().getPortAssignment_3_1_1_2(), "rule__Component__PortAssignment_3_1_1_2");
					put(grammarAccess.getComponentAccess().getNestedInterfaceAssignment_3_1_1_3(), "rule__Component__NestedInterfaceAssignment_3_1_1_3");
					put(grammarAccess.getComponentAccess().getPortRelationAssignment_3_1_1_4(), "rule__Component__PortRelationAssignment_3_1_1_4");
					put(grammarAccess.getComponentAccess().getInterfaceRelationAssignment_3_1_1_5(), "rule__Component__InterfaceRelationAssignment_3_1_1_5");
					put(grammarAccess.getGeneralizationAccess().getLeftClassifierAssignment_2(), "rule__Generalization__LeftClassifierAssignment_2");
					put(grammarAccess.getGeneralizationAccess().getRightClassifierAssignment_4(), "rule__Generalization__RightClassifierAssignment_4");
					put(grammarAccess.getAbstractionAccess().getLeftClassifierAssignment_2(), "rule__Abstraction__LeftClassifierAssignment_2");
					put(grammarAccess.getAbstractionAccess().getRightClassifierAssignment_4(), "rule__Abstraction__RightClassifierAssignment_4");
					put(grammarAccess.getManifestationAccess().getLeftClassifierAssignment_2(), "rule__Manifestation__LeftClassifierAssignment_2");
					put(grammarAccess.getManifestationAccess().getRightClassifierAssignment_4(), "rule__Manifestation__RightClassifierAssignment_4");
					put(grammarAccess.getSubstitutionAccess().getLeftClassifierAssignment_2(), "rule__Substitution__LeftClassifierAssignment_2");
					put(grammarAccess.getSubstitutionAccess().getRightClassifierAssignment_4(), "rule__Substitution__RightClassifierAssignment_4");
					put(grammarAccess.getDependencyAccess().getLeftClassifierAssignment_2(), "rule__Dependency__LeftClassifierAssignment_2");
					put(grammarAccess.getDependencyAccess().getRightClassifierAssignment_4(), "rule__Dependency__RightClassifierAssignment_4");
					put(grammarAccess.getCommentAccess().getBodyAssignment_1(), "rule__Comment__BodyAssignment_1");
					put(grammarAccess.getPortAccess().getVisibilityAssignment_1(), "rule__Port__VisibilityAssignment_1");
					put(grammarAccess.getPortAccess().getNameAssignment_3(), "rule__Port__NameAssignment_3");
					put(grammarAccess.getInterfaceAccess().getNameAssignment_2_0_0(), "rule__Interface__NameAssignment_2_0_0");
					put(grammarAccess.getInterfaceAccess().getAliasAssignment_2_0_2(), "rule__Interface__AliasAssignment_2_0_2");
					put(grammarAccess.getInterfaceAccess().getNameAssignment_2_1(), "rule__Interface__NameAssignment_2_1");
					put(grammarAccess.getInterfaceAccess().getCommentsAssignment_3_0(), "rule__Interface__CommentsAssignment_3_0");
					put(grammarAccess.getInterfaceAccess().getCommentsAssignment_3_1_1(), "rule__Interface__CommentsAssignment_3_1_1");
					put(grammarAccess.getInterfaceAccess().getMembersAssignment_3_1_2(), "rule__Interface__MembersAssignment_3_1_2");
					put(grammarAccess.getConnectorAccess().getNameAssignment_1_0_0(), "rule__Connector__NameAssignment_1_0_0");
					put(grammarAccess.getConnectorAccess().getAliasAssignment_1_0_2(), "rule__Connector__AliasAssignment_1_0_2");
					put(grammarAccess.getConnectorAccess().getNameAssignment_1_1(), "rule__Connector__NameAssignment_1_1");
					put(grammarAccess.getConnectorAccess().getOuterPortAssignment_3(), "rule__Connector__OuterPortAssignment_3");
					put(grammarAccess.getConnectorAccess().getInnerPortAssignment_5(), "rule__Connector__InnerPortAssignment_5");
					put(grammarAccess.getProvideAccess().getNameAssignment_2_0_0(), "rule__Provide__NameAssignment_2_0_0");
					put(grammarAccess.getProvideAccess().getAliasAssignment_2_0_2(), "rule__Provide__AliasAssignment_2_0_2");
					put(grammarAccess.getProvideAccess().getNameAssignment_2_1(), "rule__Provide__NameAssignment_2_1");
					put(grammarAccess.getProvideAccess().getInterfaceAssignment_3(), "rule__Provide__InterfaceAssignment_3");
					put(grammarAccess.getRequireAccess().getNameAssignment_2_0_0(), "rule__Require__NameAssignment_2_0_0");
					put(grammarAccess.getRequireAccess().getAliasAssignment_2_0_2(), "rule__Require__AliasAssignment_2_0_2");
					put(grammarAccess.getRequireAccess().getNameAssignment_2_1(), "rule__Require__NameAssignment_2_1");
					put(grammarAccess.getRequireAccess().getInterfaceAssignment_3(), "rule__Require__InterfaceAssignment_3");
					put(grammarAccess.getMethodAccess().getVisibilityAssignment_1(), "rule__Method__VisibilityAssignment_1");
					put(grammarAccess.getMethodAccess().getAbstractAssignment_2(), "rule__Method__AbstractAssignment_2");
					put(grammarAccess.getMethodAccess().getStaticAssignment_3(), "rule__Method__StaticAssignment_3");
					put(grammarAccess.getMethodAccess().getNameAssignment_4(), "rule__Method__NameAssignment_4");
					put(grammarAccess.getMethodAccess().getParametersAssignment_6_0(), "rule__Method__ParametersAssignment_6_0");
					put(grammarAccess.getMethodAccess().getParametersAssignment_6_1_1(), "rule__Method__ParametersAssignment_6_1_1");
					put(grammarAccess.getMethodAccess().getTypeAssignment_8_1(), "rule__Method__TypeAssignment_8_1");
					put(grammarAccess.getAttributeAccess().getVisibilityAssignment_1(), "rule__Attribute__VisibilityAssignment_1");
					put(grammarAccess.getAttributeAccess().getStaticAssignment_2(), "rule__Attribute__StaticAssignment_2");
					put(grammarAccess.getAttributeAccess().getNameAssignment_3(), "rule__Attribute__NameAssignment_3");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_5(), "rule__Attribute__TypeAssignment_5");
					put(grammarAccess.getParameterAccess().getVisibilityAssignment_0(), "rule__Parameter__VisibilityAssignment_0");
					put(grammarAccess.getParameterAccess().getStaticAssignment_1(), "rule__Parameter__StaticAssignment_1");
					put(grammarAccess.getParameterAccess().getNameAssignment_2(), "rule__Parameter__NameAssignment_2");
					put(grammarAccess.getParameterAccess().getTypeAssignment_4(), "rule__Parameter__TypeAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ComponentGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ComponentGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
