/*
 * generated by Xtext
 */
package de.cooperateproject.uml.xtext.clazz.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.cooperateproject.uml.xtext.clazz.services.UmlDslGrammarAccess;

public class UmlDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UmlDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.cooperateproject.uml.xtext.clazz.parser.antlr.internal.InternalUmlDslParser createParser(XtextTokenStream stream) {
		return new de.cooperateproject.uml.xtext.clazz.parser.antlr.internal.InternalUmlDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ClassDiagram";
	}
	
	public UmlDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UmlDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
