/**
 * generated by Xtext 2.11.0
 */
package de.cooperateproject.modeling.textual.sequence.sequence;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Occurence Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.cooperateproject.modeling.textual.sequence.sequence.SequencePackage#getOccurenceSpecification()
 * @model
 * @generated
 */
public interface OccurenceSpecification extends InteractionFragment
{
} // OccurenceSpecification
