/*
 * generated by Xtext 2.9.0
 */
package de.cooperateproject.modeling.textual.cls.tests

import com.google.inject.Inject
import de.cooperateproject.modeling.textual.cls.cls.ClassDiagram
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.junit4.validation.ValidationTestHelper
import de.cooperateproject.modeling.textual.cls.cls.ClassDef
import de.cooperateproject.modeling.textual.cls.cls.Name

@RunWith(XtextRunner)
@InjectWith(ClsInjectorProvider)
class ClsParsingTest{
	@Inject extension ParseHelper<ClassDiagram>
	@Inject extension ValidationTestHelper
	
	@Test
	def classDefTest() {
		val model = '''
		@startclass
		class {Alice, Bob}
		@endclass
		'''.parse
		
		val classes = (model.elements.head as ClassDef).classes
		Assert::assertEquals(2, classes.size)
		Assert::assertEquals("Alice", (classes.get(0) as Name).name)
		Assert::assertEquals("Bob", (classes.get(1) as Name).name)
	}
	
	@Test
	def interfaceDefTest() {
		val model = '''
		@startclass
		interface {Alice, Bob}
		@endclass
		'''.parse
		
		val classes = (model.elements.head as ClassDef).classes
		Assert::assertEquals(2, classes.size)
		Assert::assertEquals("Alice", (classes.get(0) as Name).name)
		Assert::assertEquals("Bob", (classes.get(1) as Name).name)
	}
}
