/*
 * generated by Xtext 2.12.0
 */
package de.cooperateproject.modeling.textual.activity.ui.refactoring.rename;

import de.cooperateproject.modeling.textual.common.metamodel.textualCommons.UMLReferencingElement;
import de.cooperateproject.modeling.textual.xtext.runtime.ui.refactoring.rename.IRenameUMLElementRefactoringFilter;
import java.util.Collection;
import java.util.Collections;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.uml2.uml.Element;

/**
 * Element filter for {@link UMLReferencingElement} elements that shall not be usable in the according rename
 * refactoring.
 */
public class ActRenameUMLElementRefactoringFilter implements IRenameUMLElementRefactoringFilter {

    private static final Collection<EClass> BLOCKED_ECLASSES = Collections.emptySet();

    @Override
    public boolean prohibitRefactoring(UMLReferencingElement<? extends Element> element) {
        return BLOCKED_ECLASSES.contains(element.eClass());
    }

}
