/*
 * generated by Xtext 2.10.0
 */
package de.cooperateproject.modeling.textual.usecase.tests

import com.google.inject.Inject
import de.cooperateproject.modeling.textual.usecase.usecase.UseCaseDiagram
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(UsecaseInjectorProvider)
class UsecaseParsingTest{

	@Inject
	ParseHelper<UseCaseDiagram> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
