/*
 * generated by Xtext 2.11.0
 */
package de.cooperateproject.modeling.textual.usecase.ui.quickfix

import de.cooperateproject.modeling.textual.xtext.runtime.ui.issues.CooperateQuickfixProvider

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
class UsecaseQuickfixProvider extends CooperateQuickfixProvider {

	new() {
		super(#[de.cooperateproject.modeling.textual.usecase.usecase.UsecasePackage.eINSTANCE])
	}

}
