/*
 * generated by Xtext
 */
package de.cooperateproject.modeling.textual.cls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ClsUiModule extends de.cooperateproject.modeling.textual.cls.ui.AbstractClsUiModule {
	public ClsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
