/*
 * generated by Xtext 2.10.0
 */
package de.cooperateproject.modeling.textual.cls.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractClsScopeProvider extends DelegatingScopeProvider {
}
