<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cls" nsURI="http://www.cooperateproject.de/modeling/textual/cls/Cls"
    nsPrefix="cls">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="rootExtendsClass" value="org.eclipse.emf.internal.cdo.CDOObjectImpl"/>
    <details key="rootExtendsInterface" value="org.eclipse.emf.cdo.CDOObject"/>
    <details key="providerRootExtendsClass" value="org.eclipse.emf.cdo.edit.CDOItemProviderAdapter"/>
    <details key="modelName" value="cls"/>
    <details key="modelDirectory" value="/de.cooperateproject.modeling.textual.cls.metamodel/src-gen"/>
    <details key="featureDelegation" value="Dynamic"/>
    <details key="basePackage" value="de.cooperateproject.modeling.textual.cls"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageImports" upperBound="-1"
        eType="#//PackageImport" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifiers" upperBound="-1"
        containment="true" resolveProxies="false">
      <eGenericType eClassifier="#//Classifier">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//Connector" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageImport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeReference" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeReference" eSuperTypes="#//TypeReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" lowerBound="1"
        eType="#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierReference" eSuperTypes="#//TypeReference #//ClassifierAssociationEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1">
      <eGenericType eClassifier="#//Classifier">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLTypeReference" eSuperTypes="#//TypeReference #//ClassifierAssociationEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLReferencingElement" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedElement" lowerBound="1">
      <eGenericType eTypeParameter="#//UMLReferencingElement/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="get" value="return getReferencedElement().getName();"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//UMLReferencingElement">
      <eTypeArguments eTypeParameter="#//NamedElement/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElementLongName" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longName" unique="false"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eGenericSuperTypes eClassifier="#//NamedElement">
      <eTypeArguments eTypeParameter="#//NamedElementLongName/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" unique="false"
        eType="#//Visibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        containment="true" resolveProxies="false">
      <eGenericType eClassifier="#//Member">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//NamedElementLongName">
      <eTypeArguments eTypeParameter="#//Classifier/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" unique="false"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//Classifier">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eGenericSuperTypes eClassifier="#//Classifier">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" unique="false"
        eType="#//Visibility"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" unique="false"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeReference"
        containment="true" resolveProxies="false"/>
    <eGenericSuperTypes eClassifier="#//NamedElement">
      <eTypeArguments eTypeParameter="#//Property/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Property">
      <eTypeArguments eTypeParameter="#//Member/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eGenericSuperTypes eClassifier="#//Member">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" unique="false"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true" resolveProxies="false"/>
    <eGenericSuperTypes eClassifier="#//Member">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eGenericSuperTypes eClassifier="#//Property">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Parameter"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" abstract="true" eSuperTypes="#//Commentable"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedConnector" abstract="true" eSuperTypes="#//Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//ClassifierAssociationEnd"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//ClassifierAssociationEnd"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//TypedConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" eType="#//AssociationProperties"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationEnd" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierAssociationEnd" abstract="true"
      interface="true" eSuperTypes="#//AssociationEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//TypedConnector"/>
  <eClassifiers xsi:type="ecore:EClass" name="Implementation" eSuperTypes="#//TypedConnector"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommentLink" eSuperTypes="#//Connector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasComment"/>
    </eAnnotations>
    <eOperations name="hasComment" unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&lt;%de.cooperateproject.modeling.textual.cls.cls.Comment%> _comment = this.getComment();&#xA;boolean _equals = &lt;%com.google.common.base.Objects%>.equal(_comment, null);&#xA;if (_equals)&#xA;{&#xA;&#x9;&lt;%java.util.ArrayList%>&lt;&lt;%java.lang.Object%>> _newArrayList = &lt;%org.eclipse.xtext.xbase.lib.CollectionLiterals%>.&lt;&lt;%java.lang.Object%>>newArrayList(this, context);&#xA;&#x9;&lt;%java.lang.Object%>[] _array = _newArrayList.toArray();&#xA;&#x9;&lt;%org.eclipse.emf.common.util.BasicDiagnostic%> _basicDiagnostic = new &lt;%org.eclipse.emf.common.util.BasicDiagnostic%>(&lt;%org.eclipse.emf.common.util.BasicDiagnostic%>.ERROR, &quot;hasComment&quot;, 1, &quot;A comment link must have a comment.&quot;, _array);&#xA;&#x9;diagnostics.add(_basicDiagnostic);&#xA;&#x9;return false;&#xA;}&#xA;diagnostics.add(&lt;%org.eclipse.emf.common.util.BasicDiagnostic%>.OK_INSTANCE);&#xA;return true;"/>
      </eAnnotations>
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//ClassifierAssociationEnd"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardinalityLeft" eType="#//Cardinality"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardinalityRight" eType="#//Cardinality"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readingDirection" unique="false"
        eType="#//ReadingDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="note" eType="#//Comment"
        containment="true" resolveProxies="false"/>
    <eGenericSuperTypes eClassifier="#//UMLReferencingElement">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cardinality">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" unique="false"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" unique="false"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commentable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="#//Comment"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
    <eLiterals name="PRIVATE" value="1"/>
    <eLiterals name="PROTECTED" value="2"/>
    <eLiterals name="PUBLIC" value="3"/>
    <eLiterals name="PACKAGE" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="INT" value="1"/>
    <eLiterals name="DOUBLE" value="2"/>
    <eLiterals name="BOOLEAN" value="3"/>
    <eLiterals name="CHAR" value="4"/>
    <eLiterals name="BYTE" value="5"/>
    <eLiterals name="SHORT" value="6"/>
    <eLiterals name="LONG" value="7"/>
    <eLiterals name="FLOAT" value="8"/>
    <eLiterals name="STRING" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReadingDirection">
    <eLiterals name="LEFT" value="1"/>
    <eLiterals name="RIGHT" value="2"/>
  </eClassifiers>
</ecore:EPackage>
