/**
 * generated by Xtext 2.11.0
 */
package de.cooperateproject.modeling.textual.sequence.sequence;

import org.eclipse.uml2.uml.InteractionFragment;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fragment Time Interval Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cooperateproject.modeling.textual.sequence.sequence.FragmentTimeIntervalSelector#getNonInstantaneousFragment <em>Non Instantaneous Fragment</em>}</li>
 * </ul>
 *
 * @see de.cooperateproject.modeling.textual.sequence.sequence.SequencePackage#getFragmentTimeIntervalSelector()
 * @model
 * @generated
 */
public interface FragmentTimeIntervalSelector extends TimeIntervalSelector {
    /**
     * Returns the value of the '<em><b>Non Instantaneous Fragment</b></em>' reference.
     * <!-- begin-user-doc -->
     * <p>
     * If the meaning of the '<em>Non Instantaneous Fragment</em>' reference isn't clear,
     * there really should be more of a description here...
     * </p>
     * <!-- end-user-doc -->
     * @return the value of the '<em>Non Instantaneous Fragment</em>' reference.
     * @see #setNonInstantaneousFragment(NonInstantaneousFragment)
     * @see de.cooperateproject.modeling.textual.sequence.sequence.SequencePackage#getFragmentTimeIntervalSelector_NonInstantaneousFragment()
     * @model
     * @generated
     */
    NonInstantaneousFragment getNonInstantaneousFragment();

    /**
     * Sets the value of the '{@link de.cooperateproject.modeling.textual.sequence.sequence.FragmentTimeIntervalSelector#getNonInstantaneousFragment <em>Non Instantaneous Fragment</em>}' reference.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @param value the new value of the '<em>Non Instantaneous Fragment</em>' reference.
     * @see #getNonInstantaneousFragment()
     * @generated
     */
    void setNonInstantaneousFragment(NonInstantaneousFragment value);

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @model kind="operation"
     *        annotation="http://www.eclipse.org/emf/2002/GenModel body='return this.getNonInstantaneousFragment();'"
     * @generated
     */
    AliasedPointInTime<? extends InteractionFragment> getIntervalStart();

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @model kind="operation"
     *        annotation="http://www.eclipse.org/emf/2002/GenModel body='return this.getNonInstantaneousFragment();'"
     * @generated
     */
    AliasedPointInTime<? extends InteractionFragment> getIntervalEnd();

} // FragmentTimeIntervalSelector
