/**
 * generated by Xtext 2.11.0
 */
package de.cooperateproject.modeling.textual.sequence.sequence;

import de.cooperateproject.modeling.textual.common.metamodel.textualCommons.NamedElement;
import de.cooperateproject.modeling.textual.common.metamodel.textualCommons.UMLReferencingElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cooperateproject.modeling.textual.sequence.sequence.Message#getOrder <em>Order</em>}</li>
 *   <li>{@link de.cooperateproject.modeling.textual.sequence.sequence.Message#getTimeConstraint <em>Time Constraint</em>}</li>
 * </ul>
 *
 * @see de.cooperateproject.modeling.textual.sequence.sequence.SequencePackage#getMessage()
 * @model
 * @generated
 */
public interface Message extends BehaviorFragment, UMLReferencingElement<org.eclipse.uml2.uml.Message>, NamedElement {
    /**
     * Returns the value of the '<em><b>Order</b></em>' attribute.
     * <!-- begin-user-doc -->
     * <p>
     * If the meaning of the '<em>Order</em>' attribute isn't clear,
     * there really should be more of a description here...
     * </p>
     * <!-- end-user-doc -->
     * @return the value of the '<em>Order</em>' attribute.
     * @see #setOrder(String)
     * @see de.cooperateproject.modeling.textual.sequence.sequence.SequencePackage#getMessage_Order()
     * @model
     * @generated
     */
    String getOrder();

    /**
     * Sets the value of the '{@link de.cooperateproject.modeling.textual.sequence.sequence.Message#getOrder <em>Order</em>}' attribute.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @param value the new value of the '<em>Order</em>' attribute.
     * @see #getOrder()
     * @generated
     */
    void setOrder(String value);

    /**
     * Returns the value of the '<em><b>Time Constraint</b></em>' containment reference.
     * <!-- begin-user-doc -->
     * <p>
     * If the meaning of the '<em>Time Constraint</em>' containment reference isn't clear,
     * there really should be more of a description here...
     * </p>
     * <!-- end-user-doc -->
     * @return the value of the '<em>Time Constraint</em>' containment reference.
     * @see #setTimeConstraint(TimeConstraint)
     * @see de.cooperateproject.modeling.textual.sequence.sequence.SequencePackage#getMessage_TimeConstraint()
     * @model containment="true"
     * @generated
     */
    TimeConstraint getTimeConstraint();

    /**
     * Sets the value of the '{@link de.cooperateproject.modeling.textual.sequence.sequence.Message#getTimeConstraint <em>Time Constraint</em>}' containment reference.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @param value the new value of the '<em>Time Constraint</em>' containment reference.
     * @see #getTimeConstraint()
     * @generated
     */
    void setTimeConstraint(TimeConstraint value);

} // Message
