/**
 * generated by Xtext 2.11.0
 */
package de.cooperateproject.modeling.textual.sequence.sequence;

import de.cooperateproject.modeling.textual.common.metamodel.textualCommons.UMLReferencingElement;

import org.eclipse.uml2.uml.NamedElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point In Time</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.cooperateproject.modeling.textual.sequence.sequence.SequencePackage#getPointInTime()
 * @model abstract="true"
 * @generated
 */
public interface PointInTime<UMLPointInTimeType extends NamedElement> extends UMLReferencingElement<UMLPointInTimeType> {
} // PointInTime
