/**
 * generated by Xtext 2.11.0
 */
package de.cooperateproject.modeling.textual.sequence.sequence;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Response Message</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.cooperateproject.modeling.textual.sequence.sequence.SequencePackage#getResponseMessage()
 * @model
 * @generated
 */
public interface ResponseMessage extends Message {
} // ResponseMessage
