/**
 * generated by Xtext 2.11.0
 */
package de.cooperateproject.modeling.textual.sequence.sequence;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Region Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cooperateproject.modeling.textual.sequence.sequence.SingleRegionContainer#getRegion <em>Region</em>}</li>
 * </ul>
 *
 * @see de.cooperateproject.modeling.textual.sequence.sequence.SequencePackage#getSingleRegionContainer()
 * @model abstract="true"
 * @generated
 */
public interface SingleRegionContainer extends CombinedFragment {
    /**
     * Returns the value of the '<em><b>Region</b></em>' containment reference.
     * <!-- begin-user-doc -->
     * <p>
     * If the meaning of the '<em>Region</em>' containment reference isn't clear,
     * there really should be more of a description here...
     * </p>
     * <!-- end-user-doc -->
     * @return the value of the '<em>Region</em>' containment reference.
     * @see #setRegion(OrderedFragmentContainer)
     * @see de.cooperateproject.modeling.textual.sequence.sequence.SequencePackage#getSingleRegionContainer_Region()
     * @model containment="true" required="true"
     *        annotation="http://www.eclipse.org/emf/2002/GenModel get='throw new UnsupportedOperationException();  // FIXME Unimplemented http://www.cooperateproject.de/modeling/textual/sequence/Sequence!SingleRegionContainer!region'"
     * @generated
     */
    OrderedFragmentContainer getRegion();

    /**
     * Sets the value of the '{@link de.cooperateproject.modeling.textual.sequence.sequence.SingleRegionContainer#getRegion <em>Region</em>}' containment reference.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @param value the new value of the '<em>Region</em>' containment reference.
     * @see #getRegion()
     * @generated
     */
    void setRegion(OrderedFragmentContainer value);

} // SingleRegionContainer
