/*
 * generated by Xtext
 */
package de.cooperateproject.uml.xtext.clazz.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.cooperateproject.uml.xtext.clazz.ui.internal.UmlDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UmlDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return UmlDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return UmlDslActivator.getInstance().getInjector(UmlDslActivator.DE_COOPERATEPROJECT_UML_XTEXT_CLAZZ_UMLDSL);
	}
	
}
