/**
 * generated by Xtext 2.9.0
 */
package de.cooperateproject.modeling.language.usecase.usecase;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Diagram</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cooperateproject.modeling.language.usecase.usecase.Diagram#getUmlModel <em>Uml Model</em>}</li>
 *   <li>{@link de.cooperateproject.modeling.language.usecase.usecase.Diagram#getTest <em>Test</em>}</li>
 *   <li>{@link de.cooperateproject.modeling.language.usecase.usecase.Diagram#getTest2 <em>Test2</em>}</li>
 *   <li>{@link de.cooperateproject.modeling.language.usecase.usecase.Diagram#getActors <em>Actors</em>}</li>
 *   <li>{@link de.cooperateproject.modeling.language.usecase.usecase.Diagram#getSystem <em>System</em>}</li>
 *   <li>{@link de.cooperateproject.modeling.language.usecase.usecase.Diagram#getAssociations <em>Associations</em>}</li>
 * </ul>
 *
 * @see de.cooperateproject.modeling.language.usecase.usecase.UsecasePackage#getDiagram()
 * @model
 * @generated
 */
public interface Diagram extends EObject
{
  /**
   * Returns the value of the '<em><b>Uml Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Uml Model</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uml Model</em>' containment reference.
   * @see #setUmlModel(UMLModelReference)
   * @see de.cooperateproject.modeling.language.usecase.usecase.UsecasePackage#getDiagram_UmlModel()
   * @model containment="true"
   * @generated
   */
  UMLModelReference getUmlModel();

  /**
   * Sets the value of the '{@link de.cooperateproject.modeling.language.usecase.usecase.Diagram#getUmlModel <em>Uml Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uml Model</em>' containment reference.
   * @see #getUmlModel()
   * @generated
   */
  void setUmlModel(UMLModelReference value);

  /**
   * Returns the value of the '<em><b>Test</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Test</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test</em>' containment reference.
   * @see #setTest(Test)
   * @see de.cooperateproject.modeling.language.usecase.usecase.UsecasePackage#getDiagram_Test()
   * @model containment="true"
   * @generated
   */
  Test getTest();

  /**
   * Sets the value of the '{@link de.cooperateproject.modeling.language.usecase.usecase.Diagram#getTest <em>Test</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Test</em>' containment reference.
   * @see #getTest()
   * @generated
   */
  void setTest(Test value);

  /**
   * Returns the value of the '<em><b>Test2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Test2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test2</em>' containment reference.
   * @see #setTest2(Test2)
   * @see de.cooperateproject.modeling.language.usecase.usecase.UsecasePackage#getDiagram_Test2()
   * @model containment="true"
   * @generated
   */
  Test2 getTest2();

  /**
   * Sets the value of the '{@link de.cooperateproject.modeling.language.usecase.usecase.Diagram#getTest2 <em>Test2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Test2</em>' containment reference.
   * @see #getTest2()
   * @generated
   */
  void setTest2(Test2 value);

  /**
   * Returns the value of the '<em><b>Actors</b></em>' containment reference list.
   * The list contents are of type {@link de.cooperateproject.modeling.language.usecase.usecase.Actor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actors</em>' containment reference list.
   * @see de.cooperateproject.modeling.language.usecase.usecase.UsecasePackage#getDiagram_Actors()
   * @model containment="true"
   * @generated
   */
  EList<Actor> getActors();

  /**
   * Returns the value of the '<em><b>System</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>System</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>System</em>' containment reference.
   * @see #setSystem(de.cooperateproject.modeling.language.usecase.usecase.System)
   * @see de.cooperateproject.modeling.language.usecase.usecase.UsecasePackage#getDiagram_System()
   * @model containment="true"
   * @generated
   */
  de.cooperateproject.modeling.language.usecase.usecase.System getSystem();

  /**
   * Sets the value of the '{@link de.cooperateproject.modeling.language.usecase.usecase.Diagram#getSystem <em>System</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>System</em>' containment reference.
   * @see #getSystem()
   * @generated
   */
  void setSystem(de.cooperateproject.modeling.language.usecase.usecase.System value);

  /**
   * Returns the value of the '<em><b>Associations</b></em>' containment reference list.
   * The list contents are of type {@link de.cooperateproject.modeling.language.usecase.usecase.Association}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Associations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Associations</em>' containment reference list.
   * @see de.cooperateproject.modeling.language.usecase.usecase.UsecasePackage#getDiagram_Associations()
   * @model containment="true"
   * @generated
   */
  EList<Association> getAssociations();

} // Diagram
