/**
 *
 * $Id$
 */
package de.cooperateproject.modeling.textual.component.metamodel.component.validation;

import de.cooperateproject.modeling.textual.common.metamodel.textualCommons.Visibility;

import org.eclipse.uml2.uml.Classifier;

/**
 * A sample validator interface for {@link de.cooperateproject.modeling.textual.component.metamodel.component.Property}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyValidator {
    boolean validate();

    boolean validateVisibility(Visibility value);
    boolean validateStatic(boolean value);
    boolean validateType(Classifier value);
}
