/**
 *
 * $Id$
 */
package de.cooperateproject.modeling.textual.component.metamodel.component.validation;

import de.cooperateproject.modeling.textual.component.metamodel.component.Classifier;
import de.cooperateproject.modeling.textual.component.metamodel.component.ClassifierRelation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.cooperateproject.modeling.textual.component.metamodel.component.RootPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RootPackageValidator {
    boolean validate();

    boolean validateRelation(EList<ClassifierRelation> value);
    boolean validateClassifier(EList<Classifier> value);

    boolean validateElementcontent(EList<Classifier> value);
}
