/**
 * generated by Xtext 2.9.0
 */
package de.cooperateproject.modeling.textual.cls.cls;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cooperateproject.modeling.textual.cls.cls.DataType#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see de.cooperateproject.modeling.textual.cls.cls.ClsPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link de.cooperateproject.modeling.textual.cls.cls.DataTypeEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see de.cooperateproject.modeling.textual.cls.cls.DataTypeEnum
   * @see #setType(DataTypeEnum)
   * @see de.cooperateproject.modeling.textual.cls.cls.ClsPackage#getDataType_Type()
   * @model
   * @generated
   */
  DataTypeEnum getType();

  /**
   * Sets the value of the '{@link de.cooperateproject.modeling.textual.cls.cls.DataType#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see de.cooperateproject.modeling.textual.cls.cls.DataTypeEnum
   * @see #getType()
   * @generated
   */
  void setType(DataTypeEnum value);

} // DataType
