/*
 * generated by Xtext
 */
package de.cooperateproject.modeling.textual.activity.ide.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.cooperateproject.modeling.textual.activity.services.ActivityGrammarAccess;

public class ActivityParser extends AbstractContentAssistParser {
	
	@Inject
	private ActivityGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.cooperateproject.modeling.textual.activity.ide.contentassist.antlr.internal.InternalActivityParser createParser() {
		de.cooperateproject.modeling.textual.activity.ide.contentassist.antlr.internal.InternalActivityParser result = new de.cooperateproject.modeling.textual.activity.ide.contentassist.antlr.internal.InternalActivityParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getActivityElementAccess().getAlternatives(), "rule__ActivityElement__Alternatives");
					put(grammarAccess.getActionAccess().getLongNameAlternatives_1_0_0(), "rule__Action__LongNameAlternatives_1_0_0");
					put(grammarAccess.getConditionEndAccess().getLongNameAlternatives_0_0_0(), "rule__ConditionEnd__LongNameAlternatives_0_0_0");
					put(grammarAccess.getForkEndAccess().getLongNameAlternatives_0_0_0(), "rule__ForkEnd__LongNameAlternatives_0_0_0");
					put(grammarAccess.getReferenceAccess().getAlternatives(), "rule__Reference__Alternatives");
					put(grammarAccess.getDefRefAccess().getAlternatives(), "rule__DefRef__Alternatives");
					put(grammarAccess.getStartAndEndEnumAccess().getAlternatives(), "rule__StartAndEndEnum__Alternatives");
					put(grammarAccess.getActivityDiagramAccess().getGroup(), "rule__ActivityDiagram__Group__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getActionAccess().getGroup_1(), "rule__Action__Group_1__0");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getConditionEndAccess().getGroup(), "rule__ConditionEnd__Group__0");
					put(grammarAccess.getConditionEndAccess().getGroup_0(), "rule__ConditionEnd__Group_0__0");
					put(grammarAccess.getForkAccess().getGroup(), "rule__Fork__Group__0");
					put(grammarAccess.getForkEndAccess().getGroup(), "rule__ForkEnd__Group__0");
					put(grammarAccess.getForkEndAccess().getGroup_0(), "rule__ForkEnd__Group_0__0");
					put(grammarAccess.getAssociationAccess().getGroup(), "rule__Association__Group__0");
					put(grammarAccess.getCommentAccess().getGroup(), "rule__Comment__Group__0");
					put(grammarAccess.getActivityDiagramAccess().getElementsAssignment_2(), "rule__ActivityDiagram__ElementsAssignment_2");
					put(grammarAccess.getActionAccess().getLongNameAssignment_1_0(), "rule__Action__LongNameAssignment_1_0");
					put(grammarAccess.getActionAccess().getNameAssignment_2(), "rule__Action__NameAssignment_2");
					put(grammarAccess.getActionAccess().getCommentAssignment_3(), "rule__Action__CommentAssignment_3");
					put(grammarAccess.getConditionAccess().getConditionStartAssignment_1(), "rule__Condition__ConditionStartAssignment_1");
					put(grammarAccess.getConditionAccess().getConditionEndAssignment_3(), "rule__Condition__ConditionEndAssignment_3");
					put(grammarAccess.getConditionAccess().getCommentAssignment_4(), "rule__Condition__CommentAssignment_4");
					put(grammarAccess.getConditionEndAccess().getLongNameAssignment_0_0(), "rule__ConditionEnd__LongNameAssignment_0_0");
					put(grammarAccess.getConditionEndAccess().getNameAssignment_1(), "rule__ConditionEnd__NameAssignment_1");
					put(grammarAccess.getForkAccess().getForkStartAssignment_1(), "rule__Fork__ForkStartAssignment_1");
					put(grammarAccess.getForkAccess().getForkEndAssignment_3(), "rule__Fork__ForkEndAssignment_3");
					put(grammarAccess.getForkAccess().getCommentAssignment_4(), "rule__Fork__CommentAssignment_4");
					put(grammarAccess.getForkEndAccess().getLongNameAssignment_0_0(), "rule__ForkEnd__LongNameAssignment_0_0");
					put(grammarAccess.getForkEndAccess().getNameAssignment_1(), "rule__ForkEnd__NameAssignment_1");
					put(grammarAccess.getAssociationAccess().getLeftAssignment_0(), "rule__Association__LeftAssignment_0");
					put(grammarAccess.getAssociationAccess().getRightAssignment_2(), "rule__Association__RightAssignment_2");
					put(grammarAccess.getAssociationAccess().getCommentAssignment_3(), "rule__Association__CommentAssignment_3");
					put(grammarAccess.getDefReferenceAccess().getTypeAssignment(), "rule__DefReference__TypeAssignment");
					put(grammarAccess.getStartAndEndAccess().getTypeAssignment(), "rule__StartAndEnd__TypeAssignment");
					put(grammarAccess.getCommentAccess().getDescriptionAssignment_1(), "rule__Comment__DescriptionAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.cooperateproject.modeling.textual.activity.ide.contentassist.antlr.internal.InternalActivityParser typedParser = (de.cooperateproject.modeling.textual.activity.ide.contentassist.antlr.internal.InternalActivityParser) parser;
			typedParser.entryRuleActivityDiagram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ActivityGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ActivityGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
