/*
 * generated by Xtext 2.12.0
 */
package de.cooperateproject.modeling.textual.activity.formatting2;

import com.google.inject.Inject;
import de.cooperateproject.modeling.textual.activity.services.ActGrammarAccess;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;

class ActFormatter extends AbstractFormatter2 {
	
	@Inject extension ActGrammarAccess
	
	override format(Object obj, IFormattableDocument document) {
		
	}
	
}
