/*
 * generated by Xtext 2.9.0
 */
package de.cooperateproject.uml.xtext.clazz.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class UmlDslOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
