/*
 * generated by Xtext 2.9.0
 */
package de.cooperateproject.modeling.textual.cls


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ClsRuntimeModule extends AbstractClsRuntimeModule {
}
