/*
 * generated by Xtext
 */
package de.cooperateproject.modeling.textual.cls.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.cooperateproject.modeling.textual.cls.services.ClsGrammarAccess;

public class ClsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ClsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.cooperateproject.modeling.textual.cls.parser.antlr.internal.InternalClsParser createParser(XtextTokenStream stream) {
		return new de.cooperateproject.modeling.textual.cls.parser.antlr.internal.InternalClsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ClassDiagram";
	}
	
	public ClsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ClsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
