/*
 * generated by Xtext 2.9.2
 */
package de.cooperateproject.modeling.textual.cls.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractClsValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.cooperateproject.modeling.textual.cls.cls.ClsPackage.eINSTANCE);
		return result;
	}
	
}
